package com.sample.service;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Thu Dec 04 14:12:27 CST 2014 
 */

public class MyZooService_PortType_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements com.sample.service.MyZooService_PortType, /**/java.io.Serializable
{

  public MyZooService_PortType_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, com.sample.service.MyZooService_PortType.class, service);
  }
  
    
  /**
   * Operation Name : {http://service.base.com/}getZooAnimals   */

  public com.base.service.Zoo getZooAnimals(com.base.service.Zoo ZooAnimalStore) throws java.rmi.RemoteException, com.base.service.Exception {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(ZooAnimalStore);
    
    try {
            java.lang.Object _result = _invoke("getZooAnimals", _args.toArray());
      return (com.base.service.Zoo)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

            if (_wls_exception instanceof com.base.service.Exception) throw (com.base.service.Exception)_wls_exception;
      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void getZooAnimalsAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.base.service.Zoo ZooAnimalStore) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "getZooAnimals");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "getZooAnimals");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "com.base.service.Zoo");
    _args.add(ZooAnimalStore);
    
    try {
      java.lang.Object _result = _invoke("getZooAnimals", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("MyZooServicePort", "MyZooServicePort");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "com.sample.service.MyZooService_Service",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}