package com.sample.service;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Dec 04 14:12:27 CST 2014 */

public class MyZooService_Service_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements com.sample.service.MyZooService_Service {

  public MyZooService_Service_Impl() throws javax.xml.rpc.ServiceException {
    this("com/sample/service/MyZooService_Service_saved_wsdl.wsdl", null);
  }
  
  public MyZooService_Service_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public MyZooService_Service_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://service.base.com/", "MyZooService"),
          "com/sample/service/MyZooService_Service_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: MyZooServicePort 
  // Port Type: MyZooService_PortType 
  //***********************************

  com.sample.service.MyZooService_PortType mvar_MyZooServicePort;

  /**
   * returns MyZooServicePort port in this service 
   */
  public com.sample.service.MyZooService_PortType getMyZooServicePort() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_MyZooServicePort == null) {
      mvar_MyZooServicePort =
        new com.sample.service.MyZooService_PortType_Stub(_getPort("MyZooServicePort"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_MyZooServicePort)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_MyZooServicePort;
  }

  /**
   * @deprecated  Use getMyZooServicePort(byte[] username, byte[] password)
   */
  public com.sample.service.MyZooService_PortType getMyZooServicePort(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getMyZooServicePort();
  }

  public com.sample.service.MyZooService_PortType getMyZooServicePort(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getMyZooServicePort();
  }
  
  
}