//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.10 at 12:02:56 PM EDT 
//


package com.base.service.person.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonStore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonStore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="personList" type="{}PersonList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonStore", propOrder = {
    "clientName",
    "personCount",
    "personList"
})
public class PersonStore {

    @XmlElement(required = true)
    protected String clientName;
    protected int personCount;
    @XmlElement(required = true)
    protected PersonList personList;

    /**
     * Gets the value of the clientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * Sets the value of the clientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientName(String value) {
        this.clientName = value;
    }

    /**
     * Gets the value of the personCount property.
     * 
     */
    public int getPersonCount() {
        return personCount;
    }

    /**
     * Sets the value of the personCount property.
     * 
     */
    public void setPersonCount(int value) {
        this.personCount = value;
    }

    /**
     * Gets the value of the personList property.
     * 
     * @return
     *     possible object is
     *     {@link PersonList }
     *     
     */
    public PersonList getPersonList() {
        return personList;
    }

    /**
     * Sets the value of the personList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonList }
     *     
     */
    public void setPersonList(PersonList value) {
        this.personList = value;
    }

}
