//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 04:37:24 PM IST 
//


package com.sample.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zoo" type="{}Zoo"/>
 *         &lt;element name="zooStoreName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zoo",
    "zooStoreName"
})
@XmlRootElement(name = "ZooStore")
public class ZooStore {

    @XmlElement(required = true)
    protected Zoo zoo;
    @XmlElement(required = true)
    protected String zooStoreName;

    /**
     * Gets the value of the zoo property.
     * 
     * @return
     *     possible object is
     *     {@link Zoo }
     *     
     */
    public Zoo getZoo() {
        return zoo;
    }

    /**
     * Sets the value of the zoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zoo }
     *     
     */
    public void setZoo(Zoo value) {
        this.zoo = value;
    }

    /**
     * Gets the value of the zooStoreName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZooStoreName() {
        return zooStoreName;
    }

    /**
     * Sets the value of the zooStoreName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZooStoreName(String value) {
        this.zooStoreName = value;
    }

}
