//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.10 at 11:48:58 AM EDT 
//


package com.base.service.zoo.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.base.service.zoo.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zoo_QNAME = new QName("", "zoo");
    private final static QName _ZooName_QNAME = new QName("", "zooName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.base.service.zoo.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zoo }
     * 
     */
    public Zoo createZoo() {
        return new Zoo();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link AnimalType }
     * 
     */
    public AnimalType createAnimalType() {
        return new AnimalType();
    }

    /**
     * Create an instance of {@link AnimalStore }
     * 
     */
    public AnimalStore createAnimalStore() {
        return new AnimalStore();
    }

    /**
     * Create an instance of {@link Animal }
     * 
     */
    public Animal createAnimal() {
        return new Animal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Zoo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zoo")
    public JAXBElement<Zoo> createZoo(Zoo value) {
        return new JAXBElement<Zoo>(_Zoo_QNAME, Zoo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zooName")
    public JAXBElement<String> createZooName(String value) {
        return new JAXBElement<String>(_ZooName_QNAME, String.class, null, value);
    }

}
