package com.sample.service;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Dec 04 14:12:27 CST 2014  
 */

public interface MyZooService_PortType extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://service.base.com/}getZooAnimals   */

  public com.base.service.Zoo getZooAnimals(com.base.service.Zoo ZooAnimalStore) throws java.rmi.RemoteException, com.base.service.Exception;
    public void getZooAnimalsAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.base.service.Zoo ZooAnimalStore) throws java.rmi.RemoteException ;
  
}