CREATE  TABLE `gncode`.`GNCODE_CASELAW_LOOKUP` (
  `ID` INT NOT NULL ,
  `COURT_NAME` VARCHAR(255) NOT NULL ,
  `NORMALIZED_COURT` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`ID`) );

CREATE  TABLE `gncode`.`GNCODE_MAPPING_INFO` (
  `gncode_id` INT NOT NULL ,
  `GNCODE_VALUE` VARCHAR(45) NULL ,
  `STATE` VARCHAR(45) NULL ,
  `COURT_TYPE` VARCHAR(45) NULL ,
  `SYSTEM` VARCHAR(45) NULL ,
  `SUBJECT_MATTER` VARCHAR(45) NULL ,
  `LOCATION` VARCHAR(45) NULL ,
  `COURT_LEVEL` VARCHAR(45) NULL ,
  `COURT_LONG_NAME` VARCHAR(255) NULL ,
  `COURT_SHORT_NAME` VARCHAR(255) NULL ,
  PRIMARY KEY (`gncode_id`) );
  
  CREATE  TABLE `gncode`.`GNCODE_MAPPING` (
  `NORMALIZED_COURT` VARCHAR(255) NOT NULL ,
  `GNCODE_ID` INT NOT NULL ,
  PRIMARY KEY (`NORMALIZED_COURT`) );


  
  CREATE  TABLE `gncode`.`gncode_jv_lookup` (
  `id` INT NOT NULL ,
  `state_name` VARCHAR(255) NULL ,
  `city_name` VARCHAR(255) NULL COMMENT '	' ,
  `county_name` VARCHAR(255) NULL ,
  `normalized_name` VARCHAR(1000) NULL ,
  PRIMARY KEY (`id`) );