package com.svmint.nomad.service;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Dec 04 12:31:37 CST 2014 */

public class ServiceServiceService_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements com.svmint.nomad.service.ServiceServiceService {

  public ServiceServiceService_Impl() throws javax.xml.rpc.ServiceException {
    this("com/svmint/nomad/service/ServiceServiceService_saved_wsdl.wsdl", null);
  }
  
  public ServiceServiceService_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public ServiceServiceService_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://service.nomad.svmint.com", "ServiceServiceService"),
          "com/svmint/nomad/service/ServiceServiceService_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: ServiceServicePort 
  // Port Type: ServiceServicePortType 
  //***********************************

  com.svmint.nomad.service.ServiceServicePortType mvar_ServiceServicePort;

  /**
   * returns ServiceServicePort port in this service 
   */
  public com.svmint.nomad.service.ServiceServicePortType getServiceServicePort() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_ServiceServicePort == null) {
      mvar_ServiceServicePort =
        new com.svmint.nomad.service.ServiceServicePortType_Stub(_getPort("ServiceServicePort"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_ServiceServicePort)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_ServiceServicePort;
  }

  /**
   * @deprecated  Use getServiceServicePort(byte[] username, byte[] password)
   */
  public com.svmint.nomad.service.ServiceServicePortType getServiceServicePort(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getServiceServicePort();
  }

  public com.svmint.nomad.service.ServiceServicePortType getServiceServicePort(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getServiceServicePort();
  }
  
  
}