package com.svmint.nomad.service;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Dec 04 12:31:37 CST 2014  
 */

public interface ServiceServicePortType extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://service.nomad.svmint.com}rtv_avail   */

  public com.svmint.nomad.service.AvailReturn rtv_Avail(com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Avail In) throws java.rmi.RemoteException;
    public void rtv_AvailAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Avail In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}sched_service   */

  public com.svmint.nomad.service.AvailReturn sched_Service(com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Avail In) throws java.rmi.RemoteException;
    public void sched_ServiceAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Avail In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}cancel_service   */

  public com.svmint.nomad.service.AptReturn cancel_Service(com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Apt In) throws java.rmi.RemoteException;
    public void cancel_ServiceAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Apt In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}cust_followup_req   */

  public com.svmint.nomad.service.Cust_Followup_ReqResponse cust_Followup_Req(com.svmint.nomad.service.Cust_Followup_Req parameters) throws java.rmi.RemoteException;
    public void cust_Followup_ReqAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.Cust_Followup_Req parameters) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}create_email   */

  public com.svmint.nomad.service.EmailReturn create_Email(com.svmint.nomad.service.User logon,com.svmint.nomad.service.Email In) throws java.rmi.RemoteException;
    public void create_EmailAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User logon,com.svmint.nomad.service.Email In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}view_notes   */

  public com.svmint.nomad.service.NotesReturn view_Notes(com.svmint.nomad.service.User logon,com.svmint.nomad.service.ActId In) throws java.rmi.RemoteException;
    public void view_NotesAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User logon,com.svmint.nomad.service.ActId In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}rtv_sched_appts   */

  public com.svmint.nomad.service.SchedApptReturn rtv_Sched_Appts(com.svmint.nomad.service.User logon,com.svmint.nomad.service.CustNum In) throws java.rmi.RemoteException;
    public void rtv_Sched_ApptsAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User logon,com.svmint.nomad.service.CustNum In) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://service.nomad.svmint.com}sched_activity   */

  public com.svmint.nomad.service.AptReturn sched_Activity(com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Schedule In) throws java.rmi.RemoteException;
    public void sched_ActivityAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.svmint.nomad.service.User Logon,com.svmint.nomad.service.Schedule In) throws java.rmi.RemoteException ;
  
}