package com.svmint.nomad.service;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Dec 04 12:31:37 CST 2014  
 */

public interface ServiceServiceService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ServiceServicePort  
     // Port Type: ServiceServicePortType   
     //***********************************
     
  /**
   * returns ServiceServicePort port in this service 
   */
  com.svmint.nomad.service.ServiceServicePortType getServiceServicePort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getServiceServicePort(byte[] username, byte[] password);
   */
  com.svmint.nomad.service.ServiceServicePortType getServiceServicePort(String username, String password) throws javax.xml.rpc.ServiceException;

  com.svmint.nomad.service.ServiceServicePortType getServiceServicePort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }